Veterinaria.App/Veterinaria.App.Presentacion/Pages/Informes/Informes.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Veterinaria.App.Dominio;
using Veterinaria.App.Persistencia;

namespace Veterinaria.App.Presentacion.Page
{
    public class InformesModel : PageModel
    {
        private static IRepositorioSugerenciaCuidado repositorioSugerenciaCuidado = new RepositorioSugerenciaCuidado(new Persistencia.AppContext());

        private static IRepositorioMascota repositorioMascota = new RepositorioMascota(new Persistencia.AppContext());

        public SugerenciaCuidado sugDeEdicion;
        public IEnumerable<SugerenciaCuidado> listaSugerenciaCuidado = new List<SugerenciaCuidado>();
        public Mascota mascotaConInforme;
/*         public String modoEdicion = "adicion";
 */



        public void listar(){

            this.listaSugerenciaCuidado = repositorioSugerenciaCuidado.GetSugerenciaCuidado();


        }

        public int bandera = 0;

        public void OnGet( int idSug)
        {          
                listar();
        }
         public void OnGetMascotaConInforme(int idMascota)
        {
            

            if (idMascota > 0)
            {
                bandera = 1;
                this.mascotaConInforme = repositorioMascota.GetMascotaConInforme(idMascota);
                
            }
            else
            {
                //this.modoEdicion ="adicion";
            }
            //this.listaMascotas = repositorioMascota.GetMascota();



        }
    }
}
/* GetMascotaConInforme */

Veterinaria.App/Veterinaria.App.Presentacion/Pages/Mascota/Mascota.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;

using Veterinaria.App.Dominio;
using Veterinaria.App.Persistencia;

namespace Veterinaria.App.Presentacion.Pages
{
    public class MascotaModel : PageModel
    {

        /* instancia obj mascota */
        private static IRepositorioMascota repositorioMascota = new RepositorioMascota(new Persistencia.AppContext());
        private static IRepositorioCuidador repositorioCuidador = new RepositorioCuidador(new Persistencia.AppContext());


        /* lista de mascotas */
        //public List<Mascotax> listaMascotas = new List<Mascotax>();
        public IEnumerable<Mascota> listaMascotas = new List<Mascota>();
        
        public Mascota mascotaDeEdicion;
        public String modoEdicion = "adicion";

        public Mascota mascotaConCitas;

        /*------  */
        private readonly ILogger<MascotaModel> _logger;

        public MascotaModel(ILogger<MascotaModel> logger)
        {
            _logger = logger;
        }

        public void OnGet( int idMascota)
        {

            if (idMascota > 0)
            {
                this.mascotaDeEdicion = repositorioMascota.GetMascota(idMascota);     
                this.modoEdicion = "edicion";
                                    
            }else
            {
                this.modoEdicion ="adicion";
            }
            
            this.listaMascotas = repositorioMascota.GetMascota();
            

        }

        public void OnPostAdd(Mascota mascotaNuevo){

            Cuidador cuidador = repositorioCuidador.GetCuidador(mascotaNuevo.CuidadorId);

            repositorioMascota.addMascota (mascotaNuevo);

            //
            this.listaMascotas = repositorioMascota.GetMascota();
        }

        public void OnPostDel(int IdMascota){
            repositorioMascota.eliminarMascota (IdMascota);

            //
            this.listaMascotas = repositorioMascota.GetMascota();
        }

        public void OnPostEdit(Mascota mascotaNuevo){
            repositorioMascota.editMascota(mascotaNuevo);
            //Console.WriteLine("nombre: " + mascotaNuevo.Especie);

            //
            this.listaMascotas = repositorioMascota.GetMascota();
        }

        public int bandera = 0;
        /*  public void OnGetMascotaConCitas(int idMascota)
        {
            

            if (idMascota > 0)
            {
                bandera = 1;
                this.mascotaConCitas = repositorioMascota.GetMascotaConCitas(idMascota);
                
            }
            else
            {
                //this.modoEdicion ="adicion";
            }
            this.listaMascotas = repositorioMascota.GetMascota();



        }

        public void OnGetMascotaConVacunas(int idMascota)
        {
            

            if (idMascota > 0)
            {
                bandera = 1;
                this.mascotaConCitas = repositorioMascota.GetMascotaConVacuna(idMascota);
                
            }
            else
            {
                //this.modoEdicion ="adicion";
            }
            //this.listaMascotas = repositorioMascota.GetMascota();



        }
         */

        
    }

   /*  public class MascotaTemporal {
        public int Id{get;set;}
        public String Nombre {get;set;}
        public String Especie {get;set;}
        public String Raza {get;set;}

        public int Edad {get;set;}
        public DateTime FechaRegistro {get;set;}


        public int CuidadorId {get;set;}
        
        public String NombreCuidador{get;set;}


    } */

}

Veterinaria.App/Veterinaria.App.Presentacion/Pages/Mascota/Mascota.cshtml
@page
@* @model IndexModel *@
@model Veterinaria.App.Presentacion.Pages.MascotaModel
@{
    ViewData["Title"] = "Gestión de la Mascota";
}

<style>
    * {
        margin: 0%;
    }

    .contenedor1 {
        display: flex;
        justify-content: space-between;
        margin-bottom: 10px;

    }

    .btn-add_mascota {
        float: left;
        padding-left: 15px;

    }

    .buscar_mascota {
        float: right;
        display: flex;
        justify-content: flex-start;
        align-items: center;
    }
</style>

<div class="text-center">
    <h1 class="display-4">Gestión de la Mascota</h1>
    
</div>



<div class="container contenedor1">
    <!-- btn agregar -->
    <div class="btn-add_mascota">
        <a href="" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Nuevo</a>
    </div>

    <!-- buscar -->
    <div class=" buscar_mascota ">
        <input type="text" class="form-control" placeholder="Buscar">
        <i class="fas fa-search"></i>
    </div>
</div>

<!-- tabla listar -->
<div class="container ">

    <div class="table-responsive  ">
        <table class="table table-striped ">
            <caption>Lista de mascotas</caption>
            <thead>
                <tr class="bg-dark" style=" color:white">
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Especie Mascota</th>
                    <th scope="col">Raza Mascota</th>
                    <th scope="col">Edad Mascota</th>
                    <th scope="col">Opciones </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model.listaMascotas)
                {


                    <tr>
                        <th scope="row">@m.Id </th>
                        <td>@m.Nombre</td>
                        <td>@m.Especie</td>
                        <td>@m.Raza</td>
                        <td>@m.Edad</td>

                        <td style="display:flex;">
                            <div style="width:50px;">
                                <form method="Post">
                                    <button class="btn btn-danger" asp-page-handler="Del" asp-route-IdMascota="@m.Id"
                                    type="submit">
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                </form>
                            </div>
                            <div style="width:50px;">

                                <button class="btn btn-success" data-toggle="modal" data-target="#ViewModal">
                                    <i class="far fa-eye"></i>
                                </button>
                            </div>
                            
                            <div style="width:50px;">

                                <a class="btn btn-warning" asp-page="/Mascota/Mascota" asp-route-IdMascota="@m.Id">
                                    <i class="far fa-edit"></i>
                                </a>
                            </div>

                            <div style="width:50px;">

                                <a class="btn btn-primary" asp-page="/Citas/Citas" asp-page-handler="MascotaConCitas" asp-route-IdMascota="@m.Id">
                                    <i class="fas fa-calendar-alt"></i>
                                </a>
                            </div>

                            <div style="width:50px;">

                                <a class="btn btn-info" asp-page="/Vacuna/Vacuna" asp-page-handler="MascotaConVacunas" asp-route-IdMascota="@m.Id">
                                    <i class="fas fa-syringe"></i>
                                </a>
                            </div>

                         


                            <a class="btn btn-secondary" asp-page="/Informes/Informes" asp-page-handler="MascotaConInforme" asp-route-IdMascota="@m.Id">
                                <i class="fas fa-sticky-note"></i>

                            </a>


                        </td>
                    </tr>


                }

                
            </tbody>
        </table>
    </div>


</div>

@* modal add mascota *@
<div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Crear Mascota</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @* form agregar mascota *@
                    <div>
                        <form method="POST">
                            <div class="form-group">
                                @* nombre mascota *@
                                <label for="add-Mascota">Nombre:</label>
                                <input type="text" class="form-control" id="name" placeholder="Nombre" name="Nombre">
                                @* Especie mascota *@
                                <label for="add-Mascota">Especie:</label>
                                <input type="text" class="form-control" id="Especie" placeholder="Especie"
                                    name="Especie">
                                @* Raza mascota *@
                                <label for="add-Mascota">Raza:</label>
                                <input type="text" class="form-control" id="Raza" placeholder="Raza" name="Raza">
                                @* Edad mascota *@
                                <label for="add-Mascota">Edad:</label>
                                <input type="number" class="form-control" id="Edad" placeholder="Edad" name="Edad">
                                
                                <label for="add-Mascota">Id:</label>
                                <input type="number" class="form-control" id="idcuidador" placeholder="Id Cuidador" name="CuidadorId">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary" asp-page-handler="Add">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

@* modal Edit mascota *@
<div>

    <!-- Modal -->
    <div class="modal fade" id="EditModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="EditModalLabel">Editar Mascota</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @* form Edit mascota *@
                    <div>
                        <form method="Post">
                            <div class="form-group">
                                <input asp-for="@Model.mascotaDeEdicion.Id" type="hidden" class="form-control" id="Nombre" placeholder="name" name="Id">
                                @* nombre mascota *@
                                <label for="add-Mascota">Nombre:</label>
                                <input asp-for="@Model.mascotaDeEdicion.Nombre" type="text" class="form-control" name="Nombre" id="name" placeholder="Nombre">
                                @* Especie mascota *@                                
                                <label for="add-Mascota">Especie:</label>
                                <input asp-for="@Model.mascotaDeEdicion.Especie" type="text" class="form-control" name="Especie" id="Especie" placeholder="Especie">
                                @* Raza mascota *@
                                <label for="add-Mascota">Raza:</label>
                                <input asp-for="@Model.mascotaDeEdicion.Raza" type="text" class="form-control" id="Raza" name="Raza" placeholder="Raza">
                                @* Edad mascota *@
                                <label for="add-Mascota">Edad:</label>
                                <input asp-for="@Model.mascotaDeEdicion.Edad" type="number" class="form-control" name="Edad" id="Edad" placeholder="Edad">
                            </div>
                            <div class="modal-footer">
                                @if (Model.modoEdicion == "edicion")
                            {
                                <button class="btn btn-primary" asp-page-handler="Edit">Guardar</button>

                            }
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>

                            </div>
                        </form>

                    </div>
                </div>
                
            </div>
        </div>
    </div>

</div>

@* modal view <o> mascota *@
<div>

    <!-- Modal -->
    <div class="modal fade" id="ViewModal" tabindex="-1" role="dialog" aria-labelledby="EditModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="EditModalLabel">Vista Mascota</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @* vista mascota *@
                    <div>
                        <div>
                            <img src="https://s1.eestatic.com/2020/08/26/curiosidades/mascotas/mascotas-perros-gatos_515959375_158488465_1706x960.jpg"
                                alt="" width="100px" height="">
                        </div>
                        <h6>Nombre:</h6>
                        <h6>descripción:</h6>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </div>
    </div>

</div>







@if (Model.modoEdicion == "edicion")
{
    <script>
        $(document).ready(function () {
            $('#EditModal').modal('toggle')
        });
    </script>

}